[project]
name = "pokedex"
requires-python = ">=3.13"
license = "MIT"
authors = [
    {name="Parnassius", email="Parnassius@users.noreply.github.com"},
]
dependencies = [
    "cattrs>=25.1.0",
    "pyyaml>=6.0.1",
]
dynamic = ["version"]

[dependency-groups]
dev = [
    "mypy==2.3.1",
    "pytest==9.1.1",
    "ruff==0.16.5",
    "types-pyyaml==6.0.12.20260815",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"


[tool.hatch.version]
source = "vcs"


[tool.mypy]
python_version = "3.13"
strict = true

# Disallow dynamic typing
disallow_any_unimported = true
#disallow_any_expr = true
disallow_any_decorated = true
disallow_any_explicit = true

show_error_codes = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "pokedex.cache.converter"
disallow_any_decorated = false
disallow_any_explicit = false


[tool.pytest]
strict = true


[tool.ruff.lint]
extend-select = [
    "A",     # flake8-builtins
    "ANN",   # flake8-annotations
    "ARG",   # flake8-unused-arguments
    "EM",    # flake8-errmsg
    "INP",   # flake8-no-pep420
    "RSE",   # flake8-raise
    "SLF",   # flake8-self
    "TID",   # flake8-tidy-imports
]
ignore = [
    "A003",  # builtin-attribute-shadowing
]
fixable = [
    "I",     # isort
    "F401",  # unused-import
    "TC",    # flake8-type-checking
    "TID",   # flake8-tidy-imports
    "UP",    # pyupgrade
]
dummy-variable-rgx = "^_$"

[tool.ruff.lint.per-file-ignores]
"src/pokedex/cache/converter.py" = [
    "ANN401",  # any-type
    "ARG001",  # unused-function-argument
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "pokedex.enums.GameGroup.get_default",
    "pokedex.enums.Language.get_default",
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.isort]
split-on-trailing-comma = false


[tool.uv]
cache-keys = [
    {file="pyproject.toml"},
    {git={commit=true}},
]
