name: ci

on: [push, pull_request]

jobs:
  editorconfig:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Setup editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2
      - name: Run editorconfig-checker
        run: editorconfig-checker

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Lint
        run: make lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04  # renovate: github-runner
          - macos-14  # renovate: github-runner
          - windows-2025  # renovate: github-runner
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "pypy3.9"
          - "pypy3.10"
          - "pypy3.11"
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Test
        run: make pytest

  dummy-required-job:
    runs-on: ubuntu-24.04
    needs: [editorconfig, lint, test]
    if: always()
    steps:
      - run: exit 1
        if: ${{ contains( needs.*.result, 'failure' ) || contains( needs.*.result, 'cancelled' ) }}
